/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorChat;
import Modelo.Cliente;
import Modelo.CryptSecurity;
import java.net.Socket;

/**
 *
 * @author viccr
 */
public class VentanaChat extends javax.swing.JFrame {

    /**
     * Creates new form VentanaChat
     */
    private Socket socket;
    private CryptSecurity cifrador;
    private Cliente cliente;
    private String tipoChat;
    
    public VentanaChat(String tipoChat) {
        initComponents();
        ControladorChat controladorC = new ControladorChat(this);
        setActionCommand(controladorC);
        cliente = new Cliente(socket, this);
        cliente.start();
        cifrador = new CryptSecurity();
        this.tipoChat=tipoChat;
        this.setLocationRelativeTo(null);

    }

    private void setActionCommand(ControladorChat controladorC) {
        btn_enviar.addActionListener(controladorC);
        btn_salir.addActionListener(controladorC);
    }

    public String getNombreChat() {
        return txt_nombreChat.getText();
    }

    public void setSocket(Socket socket) {
        this.socket = socket;
    }

    public Socket getSocket() {
        return socket;
    }

    public void setMensaje(String mensaje) throws Exception {
        // cifrador.DeCrypt(mensaje);
        txt_chat.append(" \n" + getNombreChat() + ": " + mensaje);
    }

    public void setMensajeDescifrado(String mensaje) {
        String message = "";
        message = getMensajeDescifrado(mensaje);
        txt_chat.append(message+"\n");
    }

    public void setNombre(String nombre) {
        this.lbl_name.setText(nombre);
    }

    public void setIP(String ip) {
        this.lbl_ip.setText(ip);
    }

    public void setPuerto(String puerto) {
        this.lbl_puerto.setText(puerto);
    }

    public String getNombreUsuario() {
        return lbl_name.getText();

    }

    public String getIP() {
        return lbl_ip.getText();
    }

    public int getPuerto() {
        return Integer.parseInt(lbl_puerto.getText());
    }

    public boolean validarMensaje() {
        if (txt_mensaje.getText().equalsIgnoreCase("")) {
            return false;
        } else {
            return true;
        }
    }

    
    public String getTipoChat(){
        return tipoChat;
    }
    
    public String getMensaje() {
        return txt_mensaje.getText();
    }

    public void limpiarMensaje() {
        txt_mensaje.setText("");
    }

    public String getMensajeDescifrado(String mensaje) {
        String decodeText = "";
        String[] lista;
        try {
            decodeText = cifrador.DeCrypt(mensaje);
            
            lista = decodeText.split(",");
            
            decodeText=lista[1];
            
        } catch (Exception ex) {
            System.out.println("Lo sentimos, ha ocurrido un error mientras se decodifica el mensaje");
        }
        System.out.println("El mensaje ha sido descifrado:  " + decodeText);
        return decodeText;
    }

    public String getMensajeCifrado(String tipo) {
        String mensaje = "";
        switch (tipo) {
            case "Difusion": mensaje = cifrador.crypt("Difusion,"+txt_mensaje.getText());
                break;
            case "Grupal": mensaje = cifrador.crypt("Grupal,"+txt_mensaje.getText());
                break;
            case "Privado":mensaje = cifrador.crypt("Privado,"+txt_mensaje.getText());
                break;
        }
        
        System.out.println("El mensaje cifrado es: " + mensaje);
        return mensaje;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombreChat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_chat = new javax.swing.JTextArea();
        txt_mensaje = new javax.swing.JTextField();
        btn_enviar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_puerto = new javax.swing.JLabel();
        lbl_ip = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("CHAT");

        jLabel2.setText("Nombre Chat:");

        txt_nombreChat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txt_chat.setColumns(20);
        txt_chat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_chat.setRows(5);
        jScrollPane1.setViewportView(txt_chat);

        txt_mensaje.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btn_enviar.setText("ENVIAR");

        btn_salir.setText("SALIR");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Direccion IP:");

        jLabel5.setText("Puerto:");

        lbl_name.setText(".......");

        lbl_puerto.setText("......");

        lbl_ip.setText("......");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_salir)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_enviar))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                                .addComponent(txt_mensaje, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_name)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5)
                                            .addGap(28, 28, 28)
                                            .addComponent(lbl_puerto)
                                            .addGap(36, 36, 36))
                                        .addComponent(txt_nombreChat, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_ip)))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nombreChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(lbl_name)
                    .addComponent(lbl_puerto))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbl_ip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(txt_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_enviar)
                    .addComponent(btn_salir))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VentanaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VentanaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VentanaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VentanaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VentanaChat().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enviar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ip;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_puerto;
    private javax.swing.JTextArea txt_chat;
    private javax.swing.JTextField txt_mensaje;
    private javax.swing.JTextField txt_nombreChat;
    // End of variables declaration//GEN-END:variables
}
